const {
    creep_counter,
    room_targets: room_targets_ctl,
    init_serval_workers,
    sys_log,
} = require("function");

const spawn = Game.spawns["Spawn1"];

// tower_ids
const { HRSC, CreateHRSC } = require("HR_Service_Center");

const TAG = "MAIN :";

// Game.spawns['Spawn1'].room.createConstructionSite( 23, 22, STRUCTURE_TOWER );
const stage_ploy = {
    test: "test",
    ploy: [
        {
            worker_body: [
                WORK,
                WORK,
                CARRY,
                MOVE,
            ],
            num_harvester: 6,
            num_upgrader: 6,
            num_builder: 4,
            num_recycler: 1,
            level: 1,
        },
        {
            worker_body: [
                WORK,
                WORK,
                WORK,
                CARRY,
                CARRY,
                MOVE,
                MOVE,
                MOVE,
            ],
            num_harvester: 4,
            num_upgrader: 5,
            num_builder: 1,
            num_recycler: 1,
            level: 2,
        },
        {
            worker_body: [
                WORK,
                WORK,
                WORK,
                WORK,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
            ],
            num_harvester: 3,
            num_upgrader: 3,
            num_builder: 3,
            num_recycler: 2,
            level: 3,
        },
        {
            worker_body: [
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
            ],
            num_harvester: 2,
            num_upgrader: 3,
            num_builder: 1,
            num_recycler: 1,
            level: 4,
        },
        {
            worker_body: [
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
            ],
            num_harvester: 4,
            num_upgrader: 4,
            num_builder: 2,
            num_recycler: 1,
            level: 5,
        },
        {
            worker_body: [
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
            ],
            num_harvester: 4,
            num_upgrader: 4,
            num_builder: 2,
            num_recycler: 1,
            level: 6,
        },
        {
            worker_body: [
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
            ],
            num_harvester: 4,
            num_upgrader: 4,
            num_builder: 2,
            num_recycler: 1,
            level: 7,
        },
        {
            worker_body: [
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                WORK,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                CARRY,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
                MOVE,
            ],
            num_harvester: 4,
            num_upgrader: 4,
            num_builder: 2,
            level: 8,
        },
    ],
    choise: function (room_level) {
        return this.ploy[room_level - 1];
    },
};

module.exports.loop = function () {
    const startCpu = Game.cpu.getUsed();

    const counter = creep_counter.getInstance();
    init_serval_workers(spawn, counter, stage_ploy.choise(3));

    const HR = HRSC.getInstance();
    HR.run();

    const elapsed = Game.cpu.getUsed() - startCpu;
    console.log(`${TAG} cpu has used ${elapsed} CPU time`);
    console.log(`${TAG} cpu tickLimit: ${Game.cpu.tickLimit}`);
    // for (const spawn in Game.spawns) {
    //     console.log(spawn);
    // }
};
